"""add clinical context to report analyses

Revision ID: 5c6c59c8e508
Revises: 4674c3fff0a3
Create Date: 2026-09-24 22:38:36.184159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c6c59c8e508'
down_revision: Union[str, Sequence[str], None] = '4674c3fff0a3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_analyses', sa.Column('clinical_context', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_analyses', 'clinical_context')
    # ### end Alembic commands ###
